#!/bin/bash
dir1=`pwd`
pack_name=`ls -l ${dir1} |grep kernel*.rpm |awk -F " " '{print $9}'`

rpm -ivh ${pack_name}

#修改kernel.spec ，让新内核支持ocfs2模块
line=$(cat -n $dir1/rpmbuild/SPECS/kernel.spec |grep "  mv \$i .config"|awk -F " " '{print $1}')
sed -i "${line}i\  sed -i 's\/# CONFIG_OCFS2_FS is not set\/CONFIG_OCFS2_FS=m\/' \$i" $dir1/rpmbuild/SPECS/kernel.spec
sed -i 's/\%define listnewconfig_fail 1/\%define listnewconfig_fail 0/' $dir1/rpmbuild/SPECS/kernel.spec

#重装编译一次内核包，需要很长时间
rpmbuild -ba $dir1/rpmbuild/SPECS/kernel.spec

#安装新生成的内核rpm包
rpm -qpl $dir1/rpmbuild/RPMS/x86_64/${pack_name} |grep ocfs
rpm -ivh $dir1/rpmbuild/RPMS/x86_64/${pack_name}

#设置开机启动新版内核
sudo awk -F\' '$1=="menuentry " {print i++ " : " $2}' /etc/grub2.cfg
grub2-set-default 0 
grub2-mkconfig -o /boot/grub2/grub.cfg

read -p "kernel更新已经完成，你想现在重启此系统吗？ [ yes or no ]  :" yn
if [ &yn == "y" || $yn == "yes" ]
then 
  reboot
 else
  echo "OK!"
 fi

